<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="TaskTrack.Application\**\*.cs" />
    <Compile Remove="TaskTrack.Domain\**\*.cs" />
    <Compile Remove="TaskTrack.Infrastructure\**\*.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="TaskTrack.Application\TaskTrack.Application.csproj" />
    <ProjectReference Include="TaskTrack.Infrastructure\TaskTrack.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.4" />
  </ItemGroup>

</Project>
