// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaskTrack.Api.Infrastructure.Persistence;

#nullable disable

namespace TaskTrack.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TaskTrack.Api.Domain.Entities.AprovacaoSolicitacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Aprovado")
                        .HasColumnType("boolean")
                        .HasColumnName("aprovado");

                    b.Property<DateTimeOffset?>("DataAprovacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_aprovacao");

                    b.Property<Guid>("GestorId")
                        .HasColumnType("uuid")
                        .HasColumnName("gestor_id");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<Guid>("SolicitacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("solicitacao_id");

                    b.HasKey("Id");

                    b.HasIndex("GestorId");

                    b.HasIndex("SolicitacaoId");

                    b.ToTable("aprovacoes_solicitacao", (string)null);
                });

            modelBuilder.Entity("TaskTrack.Api.Domain.Entities.Execucao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<Guid?>("AtualizadoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("atualizado_por_id");

                    b.Property<DateTimeOffset?>("DataFimReal")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_fim_real");

                    b.Property<DateTimeOffset?>("DataInicioReal")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_inicio_real");

                    b.Property<string>("ObservacaoAtualizacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao_atualizacao");

                    b.Property<Guid>("SolicitacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("solicitacao_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("AtualizadoPorId");

                    b.HasIndex("SolicitacaoId");

                    b.ToTable("execucoes", (string)null);
                });

            modelBuilder.Entity("TaskTrack.Api.Domain.Entities.LocalFilho", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("LocalPaiId")
                        .HasColumnType("uuid")
                        .HasColumnName("local_pai_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("LocalPaiId");

                    b.HasIndex("LocalPaiId", "Nome")
                        .IsUnique();

                    b.ToTable("local_filho", (string)null);
                });

            modelBuilder.Entity("TaskTrack.Api.Domain.Entities.LocalPai", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Endereco")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("endereco");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("local_pai", (string)null);
                });

            modelBuilder.Entity("TaskTrack.Api.Domain.Entities.Planejamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("DataFimPrevista")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_fim_prevista");

                    b.Property<DateTimeOffset?>("DataInicioPrevista")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_inicio_prevista");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<Guid>("SolicitacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("solicitacao_id");

                    b.HasKey("Id");

                    b.HasIndex("SolicitacaoId");

                    b.ToTable("planejamentos", (string)null);
                });

            modelBuilder.Entity("TaskTrack.Api.Domain.Entities.PlanejamentoMaterial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<Guid>("PlanejamentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("planejamento_id");

                    b.Property<decimal>("Quantidade")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("quantidade");

                    b.HasKey("Id");

                    b.HasIndex("PlanejamentoId");

                    b.ToTable("planejamento_materiais", null, t =>
                        {
                            t.HasCheckConstraint("ck_planejamento_materiais_quantidade_positiva", "quantidade > 0");
                        });
                });

            modelBuilder.Entity("TaskTrack.Api.Domain.Entities.PlanejamentoResponsavel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("PlanejamentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("planejamento_id");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("PlanejamentoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("planejamento_responsaveis", (string)null);
                });

            modelBuilder.Entity("TaskTrack.Api.Domain.Entities.Solicitacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<Guid?>("LocalFilhoId")
                        .HasColumnType("uuid")
                        .HasColumnName("local_filho_id");

                    b.Property<Guid>("LocalPaiId")
                        .HasColumnType("uuid")
                        .HasColumnName("local_pai_id");

                    b.Property<Guid>("SolicitanteId")
                        .HasColumnType("uuid")
                        .HasColumnName("solicitante_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titulo");

                    b.HasKey("Id");

                    b.HasIndex("LocalFilhoId");

                    b.HasIndex("LocalPaiId");

                    b.HasIndex("SolicitanteId");

                    b.HasIndex("LocalFilhoId", "LocalPaiId");

                    b.ToTable("solicitacoes", (string)null);
                });

            modelBuilder.Entity("TaskTrack.Api.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("TaskTrack.Api.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("TaskTrack.Api.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskTrack.Api.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("TaskTrack.Api.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaskTrack.Api.Domain.Entities.AprovacaoSolicitacao", b =>
                {
                    b.HasOne("TaskTrack.Api.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("GestorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaskTrack.Api.Domain.Entities.Solicitacao", "Solicitacao")
                        .WithMany("Aprovacoes")
                        .HasForeignKey("SolicitacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Solicitacao");
                });

            modelBuilder.Entity("TaskTrack.Api.Domain.Entities.Execucao", b =>
                {
                    b.HasOne("TaskTrack.Api.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("AtualizadoPorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TaskTrack.Api.Domain.Entities.Solicitacao", "Solicitacao")
                        .WithMany("Execucoes")
                        .HasForeignKey("SolicitacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Solicitacao");
                });

            modelBuilder.Entity("TaskTrack.Api.Domain.Entities.LocalFilho", b =>
                {
                    b.HasOne("TaskTrack.Api.Domain.Entities.LocalPai", "LocalPai")
                        .WithMany("LocaisFilho")
                        .HasForeignKey("LocalPaiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LocalPai");
                });

            modelBuilder.Entity("TaskTrack.Api.Domain.Entities.Planejamento", b =>
                {
                    b.HasOne("TaskTrack.Api.Domain.Entities.Solicitacao", "Solicitacao")
                        .WithMany("Planejamentos")
                        .HasForeignKey("SolicitacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Solicitacao");
                });

            modelBuilder.Entity("TaskTrack.Api.Domain.Entities.PlanejamentoMaterial", b =>
                {
                    b.HasOne("TaskTrack.Api.Domain.Entities.Planejamento", "Planejamento")
                        .WithMany("Materiais")
                        .HasForeignKey("PlanejamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Planejamento");
                });

            modelBuilder.Entity("TaskTrack.Api.Domain.Entities.PlanejamentoResponsavel", b =>
                {
                    b.HasOne("TaskTrack.Api.Domain.Entities.Planejamento", "Planejamento")
                        .WithMany("Responsaveis")
                        .HasForeignKey("PlanejamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskTrack.Api.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Planejamento");
                });

            modelBuilder.Entity("TaskTrack.Api.Domain.Entities.Solicitacao", b =>
                {
                    b.HasOne("TaskTrack.Api.Domain.Entities.LocalPai", "LocalPai")
                        .WithMany("Solicitacoes")
                        .HasForeignKey("LocalPaiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaskTrack.Api.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("SolicitanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaskTrack.Api.Domain.Entities.LocalFilho", "LocalFilho")
                        .WithMany("Solicitacoes")
                        .HasForeignKey("LocalFilhoId", "LocalPaiId")
                        .HasPrincipalKey("Id", "LocalPaiId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("LocalFilho");

                    b.Navigation("LocalPai");
                });

            modelBuilder.Entity("TaskTrack.Api.Domain.Entities.LocalFilho", b =>
                {
                    b.Navigation("Solicitacoes");
                });

            modelBuilder.Entity("TaskTrack.Api.Domain.Entities.LocalPai", b =>
                {
                    b.Navigation("LocaisFilho");

                    b.Navigation("Solicitacoes");
                });

            modelBuilder.Entity("TaskTrack.Api.Domain.Entities.Planejamento", b =>
                {
                    b.Navigation("Materiais");

                    b.Navigation("Responsaveis");
                });

            modelBuilder.Entity("TaskTrack.Api.Domain.Entities.Solicitacao", b =>
                {
                    b.Navigation("Aprovacoes");

                    b.Navigation("Execucoes");

                    b.Navigation("Planejamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
